rm -rf fastcgi.conf
rm -rf fastcgi.conf.default
rm -rf fastcgi_params
rm -rf fastcgi_params.default
rm -rf koi-utf
rm -rf koi-win
rm -rf mime.types
rm -rf mime.types.default
rm -rf nginx.conf.default
rm -rf scgi_params
rm -rf scgi_params.default
rm -rf uwsgi_params
rm -rf uwsgi_params.default
rm -rf win-utf
